# Collect Wikidata about floods 

```{r setup, message=FALSE,warning=FALSE}
library(glitter)
library(tidyverse)
library(sequins)
```

## Basic query

We query the Wikidata Triplestore through the {glitter} R package (ref).

```{r initial_query}
query=spq_init() %>%
    spq_add("?flood wdt:P31/wdt:P279* wd:Q8068") %>% 
    spq_add("?flood wdt:P31 ?what") %>%
    spq_add("?flood wdt:P625 ?coords",.required=FALSE) %>%
    spq_add("?flood wdt:P17 ?country",.required=FALSE) %>%
    spq_add("?flood wdt:P1120 ?deathtoll",.required=FALSE) %>%
    spq_add("?flood wdt:P276 ?loc",.required=FALSE) %>%
    spq_label(flood,country,what) 
plot_query(query, labelling=TRUE)
```
Here are the initial results we get when performing this query:

```{r run_initial_query}
if(!file.exists("data/wd_raw.RDS")){
  wd_raw=query %>%
    spq_perform(replace_prefixes=TRUE) %>% 
    mutate(deathtoll=as.numeric(deathtoll))
  saveRDS(wd_raw,"data/wd_raw.RDS")
}
wd_raw=readRDS("data/wd_raw.RDS")
kableExtra::kable(wd_raw %>% head(20))
```

This table has `r nrow(wd_raw)` rows and documents `r length(unique(wd_raw$flood))` flood events.