author:
    - name: Lise Vaudor
    - name: Liolia Bajemon
    - name: Maïlys Genouël
    - name: Hervé Piégay

project:
  type: website
  output-dir: docs

website:
  title: "glourb_floods"

  navbar:
    left:      
      - href: index.qmd
        text: Article
      - href: about.qmd
        text: About
      - href: 2_use_wikipedia.qmd
        text: Methods 1
      - href: 3_curate_wikidata.qmd
        text: Methods 2
      - href: 4_text_analysis.qmd
        text: Methods 3

      
bibliography: floods.bib

format:
  html:
    css: styles.scss
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true


editor: visual

execute:
  echo: false
  warning: false
  message: false


