project:
  type: website

website:
  title: "glourb_floods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    output-dir: docs

editor: visual

