project:
  type: website
  output-dir: docs

website:
  title: "glourb_floods"
  navbar:
    left:      
      - href: index.qmd
        text: Article
      - href: about.qmd
        text: About
      - href: 1_collect_wikidata.qmd
        text: Methods 1
      - href: 2_use_wikipedia.qmd
        text: Methods 2
      - href: 3_curate_wikidata.qmd
        text: Methods 3
      - href: 4_text_analysis.qmd
        text: Methods 4
      - href: 5_join_data.qmd
        text: Methods 5
      
bibliography: floods.bib

format:
  html:
    css: styles.scss
    theme: cosmo
    toc: true
    toc-depth: 2
    code-fold: true


editor: visual

