project:
  type: website
  output-dir: docs

website:
  title: "glourb_floods"
  navbar:
    left:      
      - href: index.qmd
        text: Article
      - href: 1_collect_wikidata.qmd
        text: Collect Wikidata
      - href: 2_use_wikipedia.qmd
        text: Collect Wikipedia-related data
      - href: 3_curate_wikidata.qmd
        text: Curate Wikidata
      - href: 4_join_data.qmd
        text: Join data and produce maps
      - href: about.qmd
        text: About
      
bibliography: floods.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

editor: visual

