---
title: "About"
---

This site gathers elements regarding flood events documented both through participatory data (Wikidata, Wikipedia) and physical (remote sensing) assessment. It questions the link between these data and what we can infer from them, in particular regarding the impact of floods on humans.

## Digital Humanities Quarterly scope:

Open Access Journal. The journal's scope includes but is not limited to:

-   Digital Tools and Methods in Humanities Research: DHQ publishes articles that showcase **innovative digital tools, methods, and approaches** used in humanities scholarship. This can involve text analysis, data visualization, digital archives, GIS (Geographic Information Systems), network analysis, and more.

-   Critical Assessment of Digital Technologies in Humanities Studies: DHQ features critical evaluations and discussions about the **implications, challenges, and limitations of using digital technologies in humanities research**. This includes considerations of ethics, accessibility, and cultural implications of digital humanities work.

-   Interdisciplinary Collaborations: The journal promotes **interdisciplinary** collaborations by highlighting research at the intersection of humanities disciplines and technology. It covers collaborations between historians, literary scholars, linguists, cultural studies scholars, and experts in computer science, data science, and information technology.

-   Digital Pedagogy and Teaching Approaches: DHQ discusses innovative pedagogical approaches that integrate digital tools and methods into humanities teaching. This includes case studies, reviews, and discussions on the use of technology in the classroom to enhance learning experiences.

-   **Digital Humanities Projects and Case Studies**: The journal publishes case studies and reports on digital humanities projects, initiatives, and experiments, providing insights into the practical application of digital methods in various humanities fields.

-   Open Access and Open Data: DHQ supports open access and open data principles, often discussing issues related to **data curation, preservation, and accessibility in the context of digital humanities research**.
